# Generated by Django 4.2.24 on 2025-09-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("code_verified", "code_verified"),
                    ("done", "done"),
                    ("photo_step", "photo_step"),
                ],
                default="new",
                max_length=31,
            ),
        ),
    ]
