# Generated by Django 4.2.24 on 2025-10-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_auth_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_type",
            field=models.CharField(
                choices=[("via_email", "via_email"), ("via_phone", "via_phone")],
                default="via_email",
                max_length=31,
            ),
        ),
    ]
