# Generated by Django 4.2.24 on 2025-10-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_postcomment_alter_commentlike_comment"),
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostComment",
        ),
    ]
